name: AFLOW inhouse build
#c++ builds: https://github.community/t/conditional-matrices/17206
#env var: https://dev.to/mihinduranasinghe/working-with-environment-variables-github-actions-part-2-46po

on: 
  workflow_dispatch:
  push:
    branches: [ master, staging ]
  pull_request:
    types: [ ready_for_review, opened, synchronize, reopened ]
    branches: [ master, staging ]
    
  #[CO20220325 - now only PR]    branches: [ master, staging ]
  #[CO20220325 - now only PR]  pull_request:
  #[CO20220325 - now only PR]    branches: [ master, staging ]
  #[HE20220701 - use self hosted runners on spin
  #[CO20220325 - now only PR]  push:
  #[CO20220325 - now only PR]    branches: [ master, staging ]
  #[CO20220325 - now only PR]  pull_request:
  #[CO20220325 - now only PR]    branches: [ master, staging ]
  #[CO20220101 - reduce time]pull_request:
  #[CO20220101 - reduce time]push:
  #[CO20220101 - reduce time]  branches: staging
  
jobs:
  build_pod_ubuntu:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -j -C src
    - name: run unit_test
      run: ./src/aflow --unit_test aurostd,database,structure
